config/routes.rb
Rails.application.routes.draw do
    root "sub#index"
  
    resources :departments do
      resources :categories  
    end
  
    resources :categories do
      resources :items
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :department
  has_many :items
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :categories
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_department 
    before_action :set_category, only: [:show, :edit, :update, :destroy]
  
    def index
      @categories = @department.categories
    end
  
    def show
    end
  
    def new
      @category = @department.categories.new
      render partial: "form"
    end
  
    def create
      @category = @department.categories.new(category_params)
  
      if @category.save
        redirect_to department_category_path(@department, @category)
        # redirect_to [@department, @category] same thing just shorthand see rails routes
      else
        render partial: "form"
      end
    end
  
    def edit
      render partial: "form"
    end
  
    def update
      if @category.update(category_params)
        redirect_to [@department, @category] # see create right above if this doesn't make sense
      else
        render :edit
      end
    end
  
    def destroy
      @category.destroy
      redirect_to department_categories_path(@department) # this is wrong on the lecture!!! if there is a department_:id on the params field(middle field) you have to pass it in your method
    end
  
    private
      def set_department
        @department = Department.find(params[:department_id])
      end
  
      def set_category
        @category = Category.find(params[:id])
      end
  
      def category_params
        params.require(:category).permit(:name)
      end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      # redirect_to departments_path(@department) or a shortcut of ....
      redirect_to department_path(@department)
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
    # redirect_to root_path - you could change that to root but if you change the root it could be problematic
  end

  private
    def department_params
      params.require(:department).permit(:name)  
    end

    def set_department
      # localhost:3000/departments/:id
      @department = Department.find(params[:id])
      #this will now call this method at the start of every method so you can delete it from edit update destroy show
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @category.items
  end

  def show
  end

  def new
    @item = @category.items.new
    render partial: "form"
  end

  def create
    @item = @category.items.new(item_params)

    if @item.save
      redirect_to category_item_path(@category, @item)
      # redirect_to [@category, @item] same thing just shorthand see rails routes
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@category, @item] # see create right above if this doesn't make sense
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to category_items_path(@category) # this is wrong on the lecture!!! if there is a category_:id on the params field(middle field) you have to pass it in your method
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name)
    end
end

app/views/categories/_form.html.erb
<h1><%= @category.id ? 'Edit Category' : 'Create Category' %></h1>
<hr />
<%= form_for [@department, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
<% end %>

app/views/categories/index.html.erb
<h1>Click a Category To View an Item</h1>
<%= link_to 'Create Categories', new_department_category_path(@department) %>
<%= link_to 'Departments', departments_path %>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, [@department, category] %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @department.name %> - <%= @category.name %></h1>
<%= link_to 'Edit category', edit_department_category_path([@department, @category]) %>
<%= link_to 'Delete category', [@department, @category], method: :delete %>
<%= link_to 'Back To categories', department_categories_path(@department) %>
<%= link_to 'View All Items', category_items_path(@category) %>

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
<% end %>
<%# <%= select_tag, @departments = option_for_select(@departments.map{|department| ["#{department.names} #{department.wonames} #{department.kids} #{department.cats}", department.id] }) %> 

app/views/departments/index.html.erb
<h1>Click a Department To View Category</h1>
<%= link_to 'Categories', @department_categories_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name, department %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Categories', department_categories_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit item' : 'Create item' %></h1>
<hr />
<%= form_for [@category, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :image %>
  <%= f.text_field :image, required: true, autofocus: true %>
  <%= f.label :description %>
  <%= f.text_field :description, required: true, autofocus: true %>
  <%= f.label :price %>
  <%= f.text_field :price, required: true, autofocus: true %>
<% end %>

app/views/items/index.html.erb
<h1>See Items</h1>
<%= link_to 'Create Item', new_category_item_path(@category) %>
<%= link_to 'Back To categories', department_categories_path(@category) %>
<ul>
<% @items.each do |item| %>
    <li><%= link_to item.name, [@category, item] %></li>
  <% end %>
</ul>

app/views/items/show.html.erb
<h1><%= @category.name %> - <%= @item.name %></h1>
<p><%= @item.name %></p>
<p><%= @item.image %></p>
<p><%= @item.description %></p>
<p><%= @item.price %></p>
<%= link_to 'Edit Item', edit_category_item_path([@category, @item]) %>
<%= link_to 'Delete Item', [@category, @item], method: :delete %>
<%= link_to 'Back To Items', category_items_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patagonia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>